path:
  ckpt_path: "./output/ckpt/OLLI_CALIBSTYLE"
  log_path: "./output/log/OLLI_CALIBSTYLE"
  result_path: "./output/result/OLLI_CALIBSTYLE"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10
step:
  meta_learning_warmup: 120000
  total_step: 400000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 20000
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 10000

